### ISSUE TITLE
[QST] Comparison to Pytorch

### ISSUE THREAD

**Issue by lukasHoel** [NVIDIA/MatX#119]
Hi, thanks for releasing MatX, I really find it interesting! I was wondering about a speed comparison to Pytorch (e.g. comparing GEMM)? I only found this and it says also 4x faster than CuPy:
https://thomasaarholt.github.io/fftspeedtest/fftspeedtest.html

But I am not too familiar with the technical details.
Do the two frameworks compare similar in terms of speed (ignoring the intended use cases of either framework)?

I appreciate your work and help! :)
Lukas

**Comment by cliffburdick** [comment]
Hi @lukasHoel, I'm assuming you're asking for a GPU-accelerated comparison of PyTorch, right? If so, I think PyTorch uses cuBLAS as a backend library (as we do too), so the results of a straight GEMM should be very similar. Where you should start to see a difference is when you perform several operations (GEMM, element-wise, etc) that are dependent on each other. In those cases, in general, Python will have a harder time knowing what it should and shouldn't leave in device memory, so you may get extra copies that aren't needed.

There are other functions besides GEMMs that you would see a larger difference just because of the way it's implemented. 

If you have some specific cases in mind for PyTorch (sizes, types, etc), let us know and we can benchmark them.

**Comment by lukasHoel** [comment]
Got it, thanks for your fast reply, yeah I was wondering about the GPU versions. It was more out of curiosity, I might give this a try for my current project and let you know if I have any specific questions

**Comment by cliffburdick** [comment]
It is strange to me that cuPy underperformed PyTorch by that much since they both should be using cuFFT. We can also validate those results over here since it's likely not the FFT that is causing the difference.

**Comment by windj007** [comment]
I'm not a pro, but it seems to me that this (https://thomasaarholt.github.io/fftspeedtest/fftspeedtest.html) benchmark is not completely correct because `torch_ifft2_fft2` (and probably other similar functions) only calls cuda implementation asynchronously, but does not wait for the result - so it might not measure actual computation time. I'm not completely sure that this is actually the case

**Comment by awthomp** [comment]
In addition to what @windj007 and @cliffburdick mentioned, this data generation call for PyTorch:

`torch.randn((x,x,2), device=device` 

creates 2 channels of (x,x) float32 samples. 

For the CuPy and NumPy tests, the data generation step explicitly casts this input data to complex128 type.

In other words, it seems the FFT benchmark, focusing exclusively on PyTorch vs CuPy, is comparing single precision complex to double precision complex.
