### ISSUE TITLE
[FEA] Jetson Support

### ISSUE THREAD

**Issue by lkskstlr** [NVIDIA/MatX#143]
Thank you for this nice library!

Is Jetson support on the horizon and if so, what is the timeline for that?

I am considering starting a project that could build on MatX but it would be vital for the project to eventually support Nvidia Jetsons.

Thanks a lot
Cheers
Lukas

**Comment by cliffburdick** [comment]
Hi @lkskstlr, since MatX requires CUDA 11, and Jetson does not have CUDA 11 yet, it cannot be used on it until that support is there. Officially support for CUDA 11 on Jetson is coming sometime in 2022, but I don't have an exact date. When it's available we will be sure to test it and make sure it works, but at until then we can't test it.

**Comment by cliffburdick** [comment]
Here is the public roadmap: https://developer.nvidia.com/embedded/develop/roadmap

**Comment by lkskstlr** [comment]
@cliffburdick thanks for the information!

**Comment by lkskstlr** [comment]
I wanted to add that I didn't know about the roadmap and that it is very cool that it is shared publicly.

**Comment by cliffburdick** [comment]
Hi @lkskstlr, it looks like a preview version with cuda 11.5 has been released:

https://developer.nvidia.com/jetpack-sdk-50dp

**Comment by cliffburdick** [comment]
@lkskstlr I was able to successfully compile and run the tests on a Jetson. The only caveat is complex fp16 gemms are broken in cuda < 11.7, so if you need that you'll have to wait until a new release.
