### ISSUE TITLE
[QST] Creating 2D view from multiple device pointers

### ISSUE THREAD

**Issue by seanajohnston** [NVIDIA/MatX#69]
Looking through the documentation [here](https://nvidia.github.io/MatX/index.html), I see the example on how to create a tensor view from device pointer. Is there any way create a single tensor view from multiple device pointers? If anything, a work around could involve copying the contents at the pointers to a single contiguous location and creating a view from that. Just looking for a way to avoid having to do that.

**Comment by cliffburdick** [comment]
Hi @seanajohnston, you are correct that you cannot use multiple device tensors to make a single tensor right now. The workaround you suggested is only a couple of lines of code now that we added the `concat` operator in the latest release: 
```
auto a = make_tensor(p1, {10}); // p1 is a device pointer
auto b = make_tensor(p2, {10}); // p2 is a device pointer
auto c = make_tensor({a.Size(0) + b.Size(0)});
(c = concat(a, b)).run();
```

The being said, we just recently pushed the ability to have more generic tensor types as part of the v0.2.0 release. This could allow what you're suggested where a type has a list of pointers and offsets where those pointers are active. Using this type will clearly be suboptimal since every access would have to branch possibly many times to compute where the pointer is on each access, but it would certainly be useful in situations where memory use is a problem.

If you think it's worthwhile given the suboptimal accesses, can you open a feature request for it?

**Comment by seanajohnston** [comment]
Excellent. At first blush, concat seems like it'll do the trick and the abstraction is simpler than cudaMemCpy's. Thanks.
