### ISSUE TITLE
[QST] How to handle variably sized batches?

### ISSUE THREAD

**Issue by deanljohnson** [NVIDIA/MatX#762]
For some batched processing problems I am working on, the problem sizes of each batch are variable.

For example, I have a set of 3d tensors that need to be permuted with something like `permute(t_data, {1, 2, 0})`. If the tensors were all the same size, I could batch the permutations with something like `permute(t_data, {3, 1, 2, 0})`. However, the tensors actually have variable sizes in the inner-most dimension ranging from 1k to 3k elements.

For the permute case, we have solved this using our own kernel with something like the following:

```
// Permute batches of matrices with variable X dimension sizes
template<typename T>
__global__ void Permute_3d_xp(const T* input, T* output, const int* x_sizes, int y_size, int z_size, int x_dim, int y_dim, int z_dim)
{
    const int batch = blockIdx.y;
    const int x_size = x_sizes[batch];

    // Shift input/output pointers to account for the varying x_sizes.
    // As long as the number of batches doesn't get too large, this should be fairly quick
    for (int i = 0; i < batch; i++)
    {
        input += x_sizes[i] * y_size * z_size;
        output += x_sizes[i] * y_size * z_size;
    }

    // input/output are now pointing to the matrix for this batch. Permute that one matrix.
    Permute_3d_device(input, output, x_size, y_size, z_size, x_dim, y_dim, z_dim);
}
```

So each thread determines the appropriate input/output offset by summing over the sizes of each tensor. In other cases, we have used pre-calculated prefix sums over sizes to determine the start of each batch of work.

We recognize this is not perfectly efficient since each batch will take a different amount of time leading lower utilization in the tail-end of the processing. However, this generally ends up being significantly faster than separate kernel launches per tensor.

`permute` is just an example. We have many operations where the processing can be batched but only if each batch is a different size. Is there any convenient way to represent these sorts of operations in `matx`?

**Comment by cliffburdick** [comment]
Hi @deanljohnson, we don't currently support "staggered" tensors, much like numpy and matlab do not either to my knowledge. There aren't many CUDA libraries that support this either, with the exception of some CUB algorithms. CUB won't give you permute, so that wouldn't help in this case.

I don't know what your `Permute_3d_device` function does, but if you wrote your own it's very likely that cuTENSOR's permute is going to be significantly faster. We found that compared to a naive `permute`, using cuTENSOR as the backend was about 4x faster and achieved SoL for memory BW. So depending on whether the actual permutation takes a significant amount of the time vs the kernel launch, cuTENSOR may be the answer here.

Currently we expose cuTENSOR by passing `-DMATX_EN_CUTENSOR=ON` to CMake, and using `einsum` to permute:

https://nvidia.github.io/MatX/api/linalg/matvec/einsum.html#permute

I would suggest doing this first, then doing a CUDA graphs capture in a loop with all your odd sizes and see how the performance stacks up. If you give us your sizes we can also benchmark it on whatever card you want, and let us know how fast your custom permute is.

**Comment by deanljohnson** [comment]
Hi @cliffburdick. I was primarily curious if there was a way to express these types of problems in `matx`.

We know that our permute implementation is quite slow. The `matx` permute is at least 4x faster when the batches are the same size and we did not use the `einsum` version. We will be switching to `permute` for non-batched and same sized batched problems and will give the `einsum` version a try. We will also try using CUDA graphs to cut-down on launch overhead for odd sized batches as an alternative to an API that directly supports staggered tensors. Thanks for the information.
